src/objects/Assigned_Task__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Assigned To is used to assign this Task to a User</description>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assigned_Task</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>This field is used to enter description about the Task</description>
        <label>Description</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>This field is used to enter Due date for a Task</description>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hourly_Rate__c</fullName>
        <description>This field is used to enter Task specific &quot;Hourly Rates&quot;</description>
        <inlineHelpText>Task specific Hourly Rates</inlineHelpText>
        <label>Hourly Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>This field is used to define a relationship between Task and Project</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Assigned Tasks</relationshipLabel>
        <relationshipName>Assigned_Task</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>This field is used to enter Start date for a Task</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Planning</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>This field is used to enter the subject of assigned task</description>
        <label>Subject</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Assigned Task</label>
    <nameField>
        <displayFormat>TASK-{0000000}</displayFormat>
        <label>Assigned Task #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assigned Task</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>This object is used to store all information about the projects within the organisation.</description>
    <fields>
        <fullName>Additional_Information__c</fullName>
        <description>This field is used to hold some additional information related to project</description>
        <label>Additional Information</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>This field is defined to track the due date of completion of project</description>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hourly_Rate__c</fullName>
        <description>This field is used to enter project specific Hourly Rate for a Employee</description>
        <inlineHelpText>Project specific &quot;Hourly Rate&quot;</inlineHelpText>
        <label>Hourly Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Scope__c</fullName>
        <description>This field is used to enter the scope/goal for the project</description>
        <label>Scope</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>This field is defined to track the starting date for the project</description>
        <inlineHelpText>Starting date for a  project</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to track the status of the project</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Done</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Member__c.object
<CustomObject>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Members</relationshipLabel>
        <relationshipName>Project_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultant</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project Members</label>
    <nameField>
        <displayFormat>MEMBER-ID-{0000000}</displayFormat>
        <label>Project Member Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Related_Task__c</fullName>
        <label>Related Task</label>
        <referenceTo>Assigned_Task__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Related_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to get select the related user for a time Entry</description>
        <label>Related User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>This field is to capture Starting Tie of a timer Entry</description>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Weekly_Time_Entry__c</fullName>
        <label>Weekly Time Entry</label>
        <referenceTo>Weekly_Time_Entry__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Related_Time_Entries</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TE-{0000000}</displayFormat>
        <label>Time Entry #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Hourly_Rate__c</fullName>
        <description>This field is to enter hourly rate for an User</description>
        <label>Hourly Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Weekly_Time_Entry__c.object
<CustomObject>
    <description>This object is used to group all Time Entries on Weekly basis</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>This field is used to capture current Week&apos;s End Date</description>
        <inlineHelpText>Week&apos;s End Date</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>This field is used to capture Current Week&apos;s Start Date</description>
        <inlineHelpText>Current Week&apos;s Start Date</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Weekly Time Entry</label>
    <nameField>
        <label>Weekly Time Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WeekLy Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TimerHelper_isTest.cls
@isTest
private class TimerHelper_isTest {

    @testSetup static void testSetup() {
        
         ID profId = UserInfo.getProfileId();
        // Create common test User
        List<User> usrList = new List<User>();
        Integer counter = 2;
        for(Integer count=0;count<counter;count++){
            String hashString = 'Q4%@' + String.valueOf(Datetime.now().formatGMT('yyyy-MM-dd HH:mm:ss.SSS'));
            Blob hash = Crypto.generateDigest('MD5', Blob.valueOf(hashString));
            String hexDigest = EncodingUtil.convertToHex(hash) + count;
            system.debug('##########' + hexDigest );
            User usr = new User(Alias = 'st'+count, Email='standarduser@testorg.com',EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',LocaleSidKey='en_US', ProfileId = ProfID,TimeZoneSidKey='America/Los_Angeles', UserName='testUser.'+hexDigest+'@testorg.com');
            usrList.add(usr);
        }
        insert usrList;
        
        // Create common test Projects
        List<Project__c> testProjects = new List<Project__c>();
        for(Integer i=0;i<2;i++) {
            testProjects.add(new Project__c(Name = 'Technical Project'+i, Additional_Information__c ='Test project', Start_Date__c=System.Today(), Due_Date__c=System.Today().addDays(14), Scope__c='Test',Status__c='In Progress', OwnerId=usrList[i].id));
        }
        insert testProjects;
        
        // Create common test Project Members
        List<Project_Member__c> testProjectMembers = new List<Project_Member__c>();
        for(Integer i=0;i<2;i++) {
            testProjectMembers.add(new Project_Member__c(Project__c = testProjects[0].id, Member__c = usrList[i].id, Role__c='Developer'));
        }
        insert testProjectMembers;
        
        // Create common test Assigned Tasks
        List< Assigned_Task__c > testAssignedTasks = new List< Assigned_Task__c >();
        for(Integer i=0;i<2;i++) {
            testAssignedTasks.add(new Assigned_Task__c(Project__c = testProjects[0].id, Assigned_To__c = usrList[i].id, Description__c ='Developer Task', Hourly_Rate__c = 200.00, Status__c = 'Planning',Start_Date__c= System.Today().addDays(2), Due_Date__c = System.Today().addDays(7) , Subject__c= 'Test Task'+i));
        }
        insert testAssignedTasks;
        
        // Create common test Assigned Tasks
        List< Weekly_Time_Entry__c > testWeeklyTimeEntries = new List< Weekly_Time_Entry__c >();
        date currrentWeek = system.TODAY().toStartofWeek();
        String currWeek_startDate = currrentWeek.format().replace('/','-');
        String currWeek_endDate = currrentWeek.addDays(6).format().replace('/','-');
        for(Integer i=0;i<2;i++) {
            testWeeklyTimeEntries.add(new Weekly_Time_Entry__c(Start_Date__c = system.TODAY().toStartofWeek(), End_Date__c=system.TODAY().toStartofWeek().addDays(6), Name= usrList[i].Name+'-'+'Week '+currWeek_startDate+'-'+currWeek_endDate ));
        }
        insert testWeeklyTimeEntries;
        
        // Create common test Assigned Tasks
        List< Time_Entry__c > testTimeEntries = new List< Time_Entry__c >();
        for(Integer i=0;i<2;i++) {
            testTimeEntries.add(new Time_Entry__c(Related_Task__c = testAssignedTasks[i].id, Related_User__c = usrList[i].id, Start_Time__c =System.Now(), Weekly_Time_Entry__c= testWeeklyTimeEntries[0].id));
        }
        insert testTimeEntries;
        
    }
    static Id TimeEntryId;
     @isTest static void testCreateTimeEntryMethod() {
        Assigned_Task__c task = [select id,name, Subject__c from Assigned_Task__c where Subject__c='Test Task1' LIMIT 1];
        if(task != NULL){
        apexpages.currentpage().getparameters().put('id' , task.id);
        system.assertEquals(apexpages.currentpage().getparameters().get('id'),task.id);
       }
       TimeEntryId= TimerHelper.createTimeEntry(task.id);
       
     }
     
    @isTest static void testOnLoadMethod() {
        Assigned_Task__c task = [select id,name, Subject__c from Assigned_Task__c where Subject__c='Test Task1' LIMIT 1];
        if(task != NULL){
        apexpages.currentpage().getparameters().put('id' , task.id);
        system.assertEquals(apexpages.currentpage().getparameters().get('id'),task.id);
       }
       String returnVal = TimerHelper.getCurrentTimeEntryDetailsremote(task.id);
     }
     
     @isTest static void testUpdateTimeEntryMethod() {
        Time_Entry__C timeEntry = [select id,name , Related_Task__r.Subject__c from Time_Entry__c where Related_Task__r.Subject__c ='Test Task1' LIMIT 1];
        if(timeEntry != NULL){
        system.assertEquals(timeEntry.Related_Task__r.Subject__c,'Test Task1');
        TimerHelper.updateTimerEntry(timeEntry.Id,'00:24:45:16','Pause');
        TimerHelper.updateTimerEntry(timeEntry.Id,'00:24:45:16','Resume');
        TimerHelper.updateTimerEntry(timeEntry.Id,'00:24:45:16','Stop');
       }
       
     }
    
    }