src/objects/User.object
<CustomObject>
    <fields>
        <fullName>WeeklyTimesheet__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field stores if weekly time sheet should be generated for this User.</description>
        <inlineHelpText>This field stores if weekly time sheet should be generated for this User.</inlineHelpText>
        <label>Weekly Timesheet</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Weekly_Time_Entry__c.object
<CustomObject>
    <description>This object is used to group all Time Entries on Weekly basis</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>This field is used to capture current Week&apos;s End Date</description>
        <inlineHelpText>Week&apos;s End Date</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>This field is used to capture Current Week&apos;s Start Date</description>
        <inlineHelpText>Current Week&apos;s Start Date</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Weekly Time Entry</label>
    <nameField>
        <label>Weekly Time Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WeekLy Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/createWeeklyTimeSheet_Batch.cls
// Batch class to create weekly time sheet recods for the users who have Weekly timesheet checkbox checked in their record.
// CreatedDate : 20 August 2016
global class createWeeklyTimeSheet_Batch implements Database.Batchable<sObject>{
global final Date dtStartDate;
global final Date dtEndDate;

global createWeeklyTimeSheet_Batch (String dtStartDt ,String dtEndDt){
     dtStartDate = Date.valueOf(dtStartDt);
    dtEndDate = Date.valueOf(dtEndDt);
    System.debug('what is the value in dtEndDate '+dtEndDate );
    System.debug('what is the value in dtStartDate '+dtStartDate );
}

global Database.QueryLocator start(Database.BatchableContext BC){
      String query = 'Select Id, Name, WeeklyTimesheet__c, isActive From User where IsActive = true AND WeeklyTimesheet__c = true';
      return Database.getQueryLocator(query);
   }

   global void execute(Database.BatchableContext BC, 
                       List<sObject> scope){
      List<Weekly_Time_Entry__c> ListWeeklyTimeSheetToBeInserted = new List<Weekly_Time_Entry__c>();                 
      for(User oUser: (List<User>)scope){
          Weekly_Time_Entry__c oRecord = new Weekly_Time_Entry__c(Name = oUser.Name+'-Week-'+String.ValueOf(dtStartDate).substring(0,10)+'-'+String.ValueOf(dtEndDate).subString(0,10) ,OwnerID = oUSer.Id,Start_Date__c=dtStartDate,End_Date__c=dtEndDate);
          ListWeeklyTimeSheetToBeInserted.add(oRecord);
      }
      System.debug('what is the value in dtEndDate '+dtEndDate );
      System.debug('what is the value in dtStartDate '+dtStartDate );
      System.debug('what is the value in ListWeeklyTimeSheetToBeInserted'+ListWeeklyTimeSheetToBeInserted);
      if(ListWeeklyTimeSheetToBeInserted.size()>0){
          List<Database.SaveResult> dsrList = Database.Insert(ListWeeklyTimeSheetToBeInserted,false);
          System.debug('what is the value in dsrList '+dsrList );
      }
   }

   global void finish(Database.BatchableContext BC){
        
   }
}